create database avaliacao_22a;
use avaliacao_22a;


INSERT INTO LIVROS (TITULO, AUTOR, ANO_PUBLICACAO, DISPONIVEL, CATEGORIA, ISBN, EDITORA, QUANTIDADE_PAGINAS, IDIOMA)
VALUES ("AS CRÔNICAS DE NÁRNIA", "C.S LEWIS", 1950, TRUE, "FANTASIA", "978-0064471190", "HARPERCOLLINS", 768, "INGLÊS");


SELECT * FROM LIVROS
WHERE TITULO = "AS CRÔNICAS DE NÁRNIA";



INSERT INTO LIVROS (TITULO, AUTOR, ANO_PUBLICACAO, DISPONIVEL, CATEGORIA, ISBN, EDITORA, QUANTIDADE_PAGINAS, IDIOMA)
VALUES ("CEM ANOS DE SOLIDÃO", "GABRIEL GARCIA MARQUEZ", 1967, TRUE, "FICÇÃO", '978-0241968581', "PENGUIN BOOKS", 422, "ESPANHOL"), ("HARRY POTTER E A PEDRA FILOSOFAL", "J.K. ROWLING", 1997, TRUE, "FANTASIA", '978-0439708180', "BLOOMSBURY", 309, "INGLÊS"), ("O SENHOR DOS ANÉIS: A SOCIEDADE DO ANEL", "J.R.R. TOLKIEN", 1954, TRUE, "FANTASIA", '978-0618640157', "HARPERCOLLINS", 423, "INGLÊS");


INSERT INTO LIVROS (TITULO, AUTOR, ANO_PUBLICACAO, DISPONIVEL, CATEGORIA, ISBN, EDITORA, QUANTIDADE_PAGINAS, IDIOMA)
VALUES ("NAPOLEÃO BOM NA PARTY", "ELMA MARIA", 1503, TRUE, "HISTÓRIA", "978-0064471191", "SHOUNEN PULO", 2, "PORTUGUÊS");


UPDATE LIVROS
SET DISPONIVEL = FALSE
WHERE ANO_PUBLICACAO < 2000;



UPDATE LIVROS
SET EDITORA = "PLUME BOOKS"
WHERE TITULO = "1984";


UPDATE LIVROS
SET IDIOMA = "INGLÊS"
WHERE EDITORA = "PENGUIN BOOKS";


UPDATE LIVROS
SET TITULO = "HARRY POTTER E A PEDRA FILOSOFAL (EDIÇÃO ESPECIAL)"
WHERE ISBN = "978-0439708180";



DELETE FROM LIVROS
WHERE CATEGORIA = "TERROR";



DELETE FROM LIVROS
WHERE IDIOMA = "FRANCÊS" AND ANO_PUBLICACAO < 1970;



DELETE FROM LIVROS
WHERE TITULO = "AS CRÔNICAS DE NÁRNIA";



DELETE FROM LIVROS
WHERE EDITORA = "PENGUIN BOOKS";



SELECT * FROM LIVROS
WHERE QUANTIDADE_PAGINAS > 500;



SELECT COUNT(CATEGORIA) FROM LIVROS
GROUP BY CATEGORIA;



SELECT * FROM LIVROS
LIMIT 0,5;



SELECT COUNT(QUANTIDADE_PAGINAS) AND SUM(QUANTIDADE_PAGINAS) FROM LIVROS
WHERE CATEGORIA = "DRAMA";



SELECT AVG(ANO_PUBLICACAO) FROM LIVROS;



SELECT MAX(ANO_PUBLICACAO), MIN(ANO_PUBLICACAO)
FROM LIVROS;


SELECT * FROM LIVROS
ORDER BY ANO_PUBLICACAO DESC;



SELECT TITULO FROM LIVROS
WHERE IDIOMA = "INGLÊS"
UNION
SELECT TITULO FROM LIVROS
WHERE IDIOMA = "PORTUGUÊS";


SELECT * FROM LIVROS
WHERE AUTOR = "GEORGE ORWELL";